# Generated by Django 5.0.6 on 2024-06-24 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_address_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.person'),
        ),
    ]
