# Generated by Django 5.0.6 on 2024-06-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_comments_todolist_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='comments',
            field=models.ManyToManyField(blank=True, to='client.comment'),
        ),
    ]
