# Generated by Django 5.0.6 on 2024-06-23 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-name'], 'verbose_name': 'Clientttt', 'verbose_name_plural': 'Clients'},
        ),
    ]
